### ISSUE TITLE
Apprentices can perform transmutations

### ISSUE THREAD

**Issue by garrettgsb** [garrettgsb/midas#19]
# Description

Right now, apprentices can be assigned to harvest resources, which is super cool. However, pretty soon, you're producing lead (probably) faster than you can transmute it-- There has to be a better way.

# Requirements

Apprentices can be assigned to transmute one resource into another, in a similar way to how they can be assigned to harvest resources. It would be good if different apprentices assigned to the same resource could have multiple transmutation targets... For example, you could have 3 apprentices transmuting Tin into Lead, and one transmuting Tin into Iron, all at the same time.

## UX idea

* User clicks "Assign" button on an Apprentice
* "Transmute to..." buttons on resources all become red, like the gather buttons do
* User clicks one of the "Transmute to..." buttons
* A little dialog pops up that lets you choose the resource to transmute to (I think this is better than just using the one that's already selected)
* The apprentice starts performing that transmutation every tick

**Comment by jholman** [comment]
I didn't pop up the little dialog, because that would have been work.
