### ISSUE TITLE
Unlockables Todo List

### ISSUE THREAD

**Issue by garrettgsb** [garrettgsb/midas#31]
How stuff unlocks is going to be an ongoing concern of the game, and much work will go into that idea. If you tackle one of these things (or notice that something is fixed), please edit the comment and do a ~~strike-thru~~ on it. If possible, reference the ticket number next to it. If you have another idea for something that should be on the list, just be a pal and add it.

## Todo: 

* UI is obviously kind of janky: New stuff kind of just pops into existence and shuffles things around suddenly. That could use some TLC.
* Come up with conditions other than "You've produced this much of a resource," such as "You've purchased this item," or "You've booped this button this many times," or "Your apprentices have booped n buttons."
* `unlocked()` is a function that takes state as a parameter right now, and Resources don't have access to global state right now... That means a Resource doesn't know its own unlocked state. This is a straightforward but slightly annoying refactor.
* Other things to make unlockable:
  - Specific items
  - Specific industries
  - Non-object things like "how many apprentices you're allowed to have" (may or may not be a completely different concept)

**Comment by jholman** [comment]
At this time, in my judgement:

* the UI is still janky
* I think that coming up with new conditions is trivial
* the "slightly annoying refactor" has been resolved
* making new things unlockable will be trivial, when and as we make those things

**Comment by garrettgsb** [comment]
Sounds about right to me.

This issue is probably rather divergent from 0.2.0 at this point... We'll leave this here for now (to keep the ideas visible), but we probably want to rethink unlockables from the ground up.
