### ISSUE TITLE
The player can cultivate a spinach garden

### ISSUE THREAD

**Issue by garrettgsb** [garrettgsb/midas#4]
Here's what I think a good bottom-tier industry would be: A spinach garden.

It produces spinach for you, but you need to harvest it yourself. What this means is that each tick, the `findVolume` of the resource increments by 1 (Or by n, per garden level... Or something) instead of the `quantity`. When you harvest it, the `findVolume` resets to 0.

Maybe the spinach maxes out at a certain number.

Maybe there's a bonus for letting the spinach reach the max number before harvesting.

Maybe you gain some other resource or benefit while the garden is maxed, a la operations/creativity in Universal Paperclips.

I think the first two might be good ideas. The third one seems kind of dumb.

**Comment by jholman** [comment]
I think that's a fine way to go with Industry.

It's not super clear if it integrates with Apprentices particularly well.  What're the relative merits of a spinach farm vs a spinach-foraging Apprentice?

I had that proposal last week that made them multiplicative with each other, which I think solved the question of "why do we have two systems", but wasn't otherwise particularly brilliant.

**Comment by garrettgsb** [comment]
I think you probably want as many apprentices as possible, operating as effectively as possible. Eventually, that gets expensive to the point that it becomes a bit of a bottleneck. When that happens, there are these other game loops to explore. 

The spinach garden, for instance, creates another interaction loop: Adjacent to the normal "Clicks/sec * value of click = output/sec" loop, the player also has the "leave for awhile then harvest" loop. 

Many resources could work like this. There could be upgrades to the rate at which they passively collect, the max they can hold, any bonuses you might get for keeping them full, and "Harvest all" or "Auto-harvest" abilities for when you end up with 10,000 spinach gardens.

I think if the player invests sufficiently in industries like these, it will be fun to have an ever-growing "trickle in," punctuated by an occasional "big bump" when you cash in your gardens (and garden-like industries).

**Comment by garrettgsb** [comment]
Oh, alternatively (and perhaps more realistically), it could be a progress bar: When it's full, you can harvest 300 spinach in one go, and the bar goes back to 0. 

We have many resources, so some could work that way, some could work as originally proposed-- It doesn't need to be one or the other.
