### ISSUE TITLE
smw feedback on makeRegistry

### ISSUE THREAD

**Issue by jholman** [garrettgsb/midas#45]
1) ditch that fucking NaN thing.  maybe a symbol would help?

2) it'd be nicer if `makeRegistry()` worked.  maybe depend on the number of arguments?  maybe make a wrapper function?

**Comment by garrettgsb** [comment]
Lol that NaN thing was a little goofy. I don't know what smw means... "Shake my wings?"

**Comment by garrettgsb** [comment]
[Urban Dictionary](https://www.urbandictionary.com/define.php?term=SMW) unfruitful.

**Comment by jholman** [comment]
sam meech-ward
